// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wau_profile.proto

package profilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =============================================================================
// 1. Profile 实体
// =============================================================================
//
// 跟 wau-intent 仓 service/profile_client.go 的 StaticProfile 字段完全对齐:
//
//	StaticProfile = {
//	  UserID          string   ← Profile.user_id
//	  Role            string   ← Profile.role
//	  Department      string   ← Profile.department
//	  PreferredSkills []string ← Profile.preferred_skills
//	  PreferredAgents []string ← Profile.preferred_agents
//	}
//
// 不存敏感字段(D9 拒收)。
type Profile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 主键,必填,空 → ErrInvalidArgument
	Role            string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`                   // doctor / developer / trader / general
	Department      string                 `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`       // healthcare / engineering / finance / unknown
	PreferredSkills []string               `protobuf:"bytes,4,rep,name=preferred_skills,json=preferredSkills,proto3" json:"preferred_skills,omitempty"`
	PreferredAgents []string               `protobuf:"bytes,5,rep,name=preferred_agents,json=preferredAgents,proto3" json:"preferred_agents,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_wau_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_wau_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_wau_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Profile) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Profile) GetPreferredSkills() []string {
	if x != nil {
		return x.PreferredSkills
	}
	return nil
}

func (x *Profile) GetPreferredAgents() []string {
	if x != nil {
		return x.PreferredAgents
	}
	return nil
}

// =============================================================================
// 2. GetProfile (主路径,被 wau-intent M2-3 调)
// =============================================================================
type GetProfileRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// M2-1 接受但不强制校验
	// M2-2 强制白名单(caller tenant 必须在 allowed 列表)
	TenantId      string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_wau_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_wau_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`                    // 找不到 → 空,not_found=true
	NotFound      bool                   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"` // 找不到时返 true(让 caller 决定是否用 EmptyProfile)
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                      // "memory-store" / "redis" / "fallback-empty"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_wau_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_wau_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GetProfileResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

func (x *GetProfileResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// =============================================================================
// 3. SetProfile (管理端)
// =============================================================================
type SetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`                   // user_id 必填
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // M2-1 接受但不强制校验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProfileRequest) Reset() {
	*x = SetProfileRequest{}
	mi := &file_wau_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileRequest) ProtoMessage() {}

func (x *SetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileRequest.ProtoReflect.Descriptor instead.
func (*SetProfileRequest) Descriptor() ([]byte, []int) {
	return file_wau_profile_proto_rawDescGZIP(), []int{3}
}

func (x *SetProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *SetProfileRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SetProfileResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// D9 拒收时返被拒字段名(debug 友好)
	// 成功时为空字符串
	ErrorField    string `protobuf:"bytes,2,opt,name=error_field,json=errorField,proto3" json:"error_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetProfileResponse) Reset() {
	*x = SetProfileResponse{}
	mi := &file_wau_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileResponse) ProtoMessage() {}

func (x *SetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileResponse.ProtoReflect.Descriptor instead.
func (*SetProfileResponse) Descriptor() ([]byte, []int) {
	return file_wau_profile_proto_rawDescGZIP(), []int{4}
}

func (x *SetProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetProfileResponse) GetErrorField() string {
	if x != nil {
		return x.ErrorField
	}
	return ""
}

// =============================================================================
// 4. DeleteProfile (GDPR / 用户注销)
// =============================================================================
type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_wau_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_wau_profile_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteProfileRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotFound      bool                   `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_wau_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_wau_profile_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteProfileResponse) GetNotFound() bool {
	if x != nil {
		return x.NotFound
	}
	return false
}

// =============================================================================
// 5. 空消息(预留)
// =============================================================================
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_wau_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_wau_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_wau_profile_proto_rawDescGZIP(), []int{7}
}

var File_wau_profile_proto protoreflect.FileDescriptor

const file_wau_profile_proto_rawDesc = "" +
	"\n" +
	"\x11wau_profile.proto\x12\x0ewau.profile.v1\"\xac\x01\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1e\n" +
	"\n" +
	"department\x18\x03 \x01(\tR\n" +
	"department\x12)\n" +
	"\x10preferred_skills\x18\x04 \x03(\tR\x0fpreferredSkills\x12)\n" +
	"\x10preferred_agents\x18\x05 \x03(\tR\x0fpreferredAgents\"I\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"|\n" +
	"\x12GetProfileResponse\x121\n" +
	"\aprofile\x18\x01 \x01(\v2\x17.wau.profile.v1.ProfileR\aprofile\x12\x1b\n" +
	"\tnot_found\x18\x02 \x01(\bR\bnotFound\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"c\n" +
	"\x11SetProfileRequest\x121\n" +
	"\aprofile\x18\x01 \x01(\v2\x17.wau.profile.v1.ProfileR\aprofile\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"O\n" +
	"\x12SetProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\verror_field\x18\x02 \x01(\tR\n" +
	"errorField\"L\n" +
	"\x14DeleteProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"N\n" +
	"\x15DeleteProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tnot_found\x18\x02 \x01(\bR\bnotFound\"\a\n" +
	"\x05Empty2\x98\x02\n" +
	"\x0eProfileService\x12S\n" +
	"\n" +
	"GetProfile\x12!.wau.profile.v1.GetProfileRequest\x1a\".wau.profile.v1.GetProfileResponse\x12S\n" +
	"\n" +
	"SetProfile\x12!.wau.profile.v1.SetProfileRequest\x1a\".wau.profile.v1.SetProfileResponse\x12\\\n" +
	"\rDeleteProfile\x12$.wau.profile.v1.DeleteProfileRequest\x1a%.wau.profile.v1.DeleteProfileResponseB,Z*github.com/wau/profile/profilev1;profilev1b\x06proto3"

var (
	file_wau_profile_proto_rawDescOnce sync.Once
	file_wau_profile_proto_rawDescData []byte
)

func file_wau_profile_proto_rawDescGZIP() []byte {
	file_wau_profile_proto_rawDescOnce.Do(func() {
		file_wau_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wau_profile_proto_rawDesc), len(file_wau_profile_proto_rawDesc)))
	})
	return file_wau_profile_proto_rawDescData
}

var file_wau_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wau_profile_proto_goTypes = []any{
	(*Profile)(nil),               // 0: wau.profile.v1.Profile
	(*GetProfileRequest)(nil),     // 1: wau.profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),    // 2: wau.profile.v1.GetProfileResponse
	(*SetProfileRequest)(nil),     // 3: wau.profile.v1.SetProfileRequest
	(*SetProfileResponse)(nil),    // 4: wau.profile.v1.SetProfileResponse
	(*DeleteProfileRequest)(nil),  // 5: wau.profile.v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil), // 6: wau.profile.v1.DeleteProfileResponse
	(*Empty)(nil),                 // 7: wau.profile.v1.Empty
}
var file_wau_profile_proto_depIdxs = []int32{
	0, // 0: wau.profile.v1.GetProfileResponse.profile:type_name -> wau.profile.v1.Profile
	0, // 1: wau.profile.v1.SetProfileRequest.profile:type_name -> wau.profile.v1.Profile
	1, // 2: wau.profile.v1.ProfileService.GetProfile:input_type -> wau.profile.v1.GetProfileRequest
	3, // 3: wau.profile.v1.ProfileService.SetProfile:input_type -> wau.profile.v1.SetProfileRequest
	5, // 4: wau.profile.v1.ProfileService.DeleteProfile:input_type -> wau.profile.v1.DeleteProfileRequest
	2, // 5: wau.profile.v1.ProfileService.GetProfile:output_type -> wau.profile.v1.GetProfileResponse
	4, // 6: wau.profile.v1.ProfileService.SetProfile:output_type -> wau.profile.v1.SetProfileResponse
	6, // 7: wau.profile.v1.ProfileService.DeleteProfile:output_type -> wau.profile.v1.DeleteProfileResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wau_profile_proto_init() }
func file_wau_profile_proto_init() {
	if File_wau_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wau_profile_proto_rawDesc), len(file_wau_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wau_profile_proto_goTypes,
		DependencyIndexes: file_wau_profile_proto_depIdxs,
		MessageInfos:      file_wau_profile_proto_msgTypes,
	}.Build()
	File_wau_profile_proto = out.File
	file_wau_profile_proto_goTypes = nil
	file_wau_profile_proto_depIdxs = nil
}
